import type { SupportedLanguage } from "./i18n";

/**
 * Curated bank of example prompts shown under the input on the home /
 * empty-chat views. Three chips are picked at random from this bank
 * once per session so the home page reads as a real product, not a
 * three-button demo. The selection is stable across rerenders within
 * a session — see `useExampleQuestions` in ChatView / HomeView for the
 * picker.
 *
 * Coverage is intentionally broad — symptoms, common medications,
 * pediatrics, mental-health, test results, and "preparing for a doctor
 * visit" — so a returning user is unlikely to see the same suggestions
 * twice in a row, and every shown chip leads to a productive flow
 * supported by the medical card pipeline.
 *
 * Per-language banks are provided for the major MedOS audiences. For
 * languages without a curated list we fall back to the English bank
 * via `getExampleQuestions()` — better than missing chips and easy to
 * extend later without touching call-sites.
 */

const EXAMPLES_EN: string[] = [
  // Common symptoms — adult
  "I have chest pain",
  "I have a headache",
  "I have stomach pain",
  "I have back pain",
  "I have shortness of breath",
  "I have a sore throat",
  "I have a persistent cough",
  "I have nausea",
  "I have diarrhea",
  "I have been vomiting",
  "I have a rash on my skin",
  "I have ear pain",
  "I have eye redness",
  "I have leg swelling",
  "I have pain when urinating",
  "I have heartburn",
  "I feel dizzy",
  "I feel very tired",
  "I have trouble sleeping",
  // Mental health
  "I have anxiety symptoms",
  "I feel depressed",
  "I had a panic attack",
  // Pain — specific
  "I have a toothache",
  "I have knee pain",
  "I have shoulder pain",
  "I twisted my ankle",
  // Injuries
  "I cut my finger",
  "I burned my hand",
  // Chronic / measurements
  "My blood pressure is high",
  "My blood sugar is high",
  "My temperature is 39°C",
  // Pediatrics
  "My child has a fever",
  "My baby has a fever",
  "My child has a cough",
  "My child has diarrhea",
  // Medication questions
  "Can I take ibuprofen?",
  "Can I take paracetamol?",
  "Can I mix these medicines?",
  "What are the side effects of this medicine?",
  "I missed a medication dose",
  // Test results & doctor prep
  "Help me understand my blood test",
  "Help me understand my urine test",
  "Help me prepare for a doctor visit",
  "Create questions for my doctor",
  "I need a doctor summary",
  // Triage & navigation
  "What symptoms should I watch for?",
  "When should I seek urgent care?",
  "Find nearby care",
  // Tracking & follow-up
  "How can I track my symptoms?",
  "What should I do before my appointment?",
];

const EXAMPLES_ES: string[] = [
  "Tengo dolor de pecho",
  "Tengo dolor de cabeza",
  "Tengo dolor de estómago",
  "Tengo dolor de espalda",
  "Tengo dificultad para respirar",
  "Tengo dolor de garganta",
  "Tengo tos persistente",
  "Tengo náuseas",
  "Tengo diarrea",
  "He estado vomitando",
  "Tengo un sarpullido",
  "Tengo dolor de oído",
  "Tengo los ojos rojos",
  "Tengo las piernas hinchadas",
  "Me duele al orinar",
  "Tengo acidez estomacal",
  "Me siento mareado",
  "Me siento muy cansado",
  "Tengo problemas para dormir",
  "Tengo síntomas de ansiedad",
  "Me siento deprimido",
  "Tuve un ataque de pánico",
  "Tengo dolor de muela",
  "Me duele la rodilla",
  "Me duele el hombro",
  "Me torcí el tobillo",
  "Me corté el dedo",
  "Me quemé la mano",
  "Tengo la presión alta",
  "Tengo el azúcar alta",
  "Mi temperatura es 39 °C",
  "Mi hijo tiene fiebre",
  "Mi bebé tiene fiebre",
  "Mi hijo tiene tos",
  "Mi hijo tiene diarrea",
  "¿Puedo tomar ibuprofeno?",
  "¿Puedo tomar paracetamol?",
  "¿Puedo mezclar estos medicamentos?",
  "¿Cuáles son los efectos secundarios de este medicamento?",
  "Olvidé tomar una dosis",
  "Ayúdame a entender mi análisis de sangre",
  "Ayúdame a entender mi análisis de orina",
  "Ayúdame a prepararme para una cita médica",
  "Crea preguntas para mi médico",
  "Necesito un resumen para el médico",
  "¿Qué síntomas debo vigilar?",
  "¿Cuándo debo buscar atención urgente?",
  "Encuentra atención cercana",
  "¿Cómo puedo registrar mis síntomas?",
  "¿Qué debo hacer antes de mi cita?",
];

const EXAMPLES_FR: string[] = [
  "J'ai une douleur à la poitrine",
  "J'ai mal à la tête",
  "J'ai mal au ventre",
  "J'ai mal au dos",
  "J'ai du mal à respirer",
  "J'ai mal à la gorge",
  "J'ai une toux persistante",
  "J'ai des nausées",
  "J'ai la diarrhée",
  "J'ai vomi plusieurs fois",
  "J'ai une éruption cutanée",
  "J'ai mal à l'oreille",
  "J'ai les yeux rouges",
  "J'ai les jambes enflées",
  "J'ai mal en urinant",
  "J'ai des brûlures d'estomac",
  "J'ai des vertiges",
  "Je me sens très fatigué",
  "J'ai des troubles du sommeil",
  "J'ai des symptômes d'anxiété",
  "Je me sens déprimé",
  "J'ai eu une crise de panique",
  "J'ai mal aux dents",
  "J'ai mal au genou",
  "J'ai mal à l'épaule",
  "Je me suis tordu la cheville",
  "Je me suis coupé le doigt",
  "Je me suis brûlé la main",
  "Ma tension est élevée",
  "Ma glycémie est élevée",
  "Ma température est de 39 °C",
  "Mon enfant a de la fièvre",
  "Mon bébé a de la fièvre",
  "Mon enfant tousse",
  "Mon enfant a la diarrhée",
  "Puis-je prendre de l'ibuprofène ?",
  "Puis-je prendre du paracétamol ?",
  "Puis-je mélanger ces médicaments ?",
  "Quels sont les effets secondaires de ce médicament ?",
  "J'ai oublié une dose de médicament",
  "Aidez-moi à comprendre ma prise de sang",
  "Aidez-moi à comprendre mon analyse d'urine",
  "Aidez-moi à préparer un rendez-vous médical",
  "Préparez des questions pour mon médecin",
  "J'ai besoin d'un résumé médical",
  "Quels symptômes dois-je surveiller ?",
  "Quand dois-je consulter en urgence ?",
  "Trouver des soins à proximité",
  "Comment suivre mes symptômes ?",
  "Que faire avant mon rendez-vous ?",
];

const EXAMPLES_IT: string[] = [
  "Ho dolore al petto",
  "Ho mal di testa",
  "Ho mal di stomaco",
  "Ho mal di schiena",
  "Ho difficoltà a respirare",
  "Ho mal di gola",
  "Ho una tosse persistente",
  "Ho la nausea",
  "Ho la diarrea",
  "Ho vomitato più volte",
  "Ho un'eruzione cutanea",
  "Ho mal d'orecchio",
  "Ho gli occhi rossi",
  "Ho le gambe gonfie",
  "Ho dolore quando urino",
  "Ho bruciore di stomaco",
  "Mi sento stordito",
  "Mi sento molto stanco",
  "Ho problemi a dormire",
  "Ho sintomi di ansia",
  "Mi sento depresso",
  "Ho avuto un attacco di panico",
  "Ho mal di denti",
  "Mi fa male il ginocchio",
  "Mi fa male la spalla",
  "Mi sono storto la caviglia",
  "Mi sono tagliato un dito",
  "Mi sono ustionato la mano",
  "Ho la pressione alta",
  "Ho la glicemia alta",
  "La mia temperatura è 39 °C",
  "Mio figlio ha la febbre",
  "Il mio bambino ha la febbre",
  "Mio figlio ha la tosse",
  "Mio figlio ha la diarrea",
  "Posso prendere ibuprofene?",
  "Posso prendere paracetamolo?",
  "Posso assumere insieme questi farmaci?",
  "Quali sono gli effetti collaterali di questo farmaco?",
  "Ho saltato una dose di farmaco",
  "Aiutami a capire le mie analisi del sangue",
  "Aiutami a capire l'esame delle urine",
  "Aiutami a prepararmi per una visita medica",
  "Crea domande per il mio medico",
  "Ho bisogno di un riassunto per il medico",
  "Quali sintomi devo tenere d'occhio?",
  "Quando devo cercare cure urgenti?",
  "Trova assistenza nelle vicinanze",
  "Come posso monitorare i miei sintomi?",
  "Cosa devo fare prima dell'appuntamento?",
];

const EXAMPLES_PT: string[] = [
  "Tenho dor no peito",
  "Tenho dor de cabeça",
  "Tenho dor de estômago",
  "Tenho dor nas costas",
  "Tenho falta de ar",
  "Tenho dor de garganta",
  "Tenho tosse persistente",
  "Tenho náuseas",
  "Tenho diarreia",
  "Tenho vomitado",
  "Tenho uma erupção na pele",
  "Tenho dor de ouvido",
  "Estou com os olhos vermelhos",
  "Tenho as pernas inchadas",
  "Sinto dor ao urinar",
  "Tenho azia",
  "Sinto tontura",
  "Sinto-me muito cansado",
  "Tenho dificuldade para dormir",
  "Tenho sintomas de ansiedade",
  "Sinto-me deprimido",
  "Tive um ataque de pânico",
  "Tenho dor de dente",
  "Sinto dor no joelho",
  "Sinto dor no ombro",
  "Torci o tornozelo",
  "Cortei o dedo",
  "Queimei a mão",
  "Minha pressão está alta",
  "Meu açúcar no sangue está alto",
  "Minha temperatura é 39 °C",
  "Meu filho está com febre",
  "Meu bebê está com febre",
  "Meu filho está com tosse",
  "Meu filho está com diarreia",
  "Posso tomar ibuprofeno?",
  "Posso tomar paracetamol?",
  "Posso misturar estes remédios?",
  "Quais são os efeitos colaterais deste remédio?",
  "Esqueci de tomar uma dose",
  "Ajude-me a entender meu exame de sangue",
  "Ajude-me a entender meu exame de urina",
  "Ajude-me a preparar a consulta médica",
  "Crie perguntas para o meu médico",
  "Preciso de um resumo para o médico",
  "Que sintomas devo observar?",
  "Quando devo procurar atendimento urgente?",
  "Encontrar atendimento próximo",
  "Como posso registrar meus sintomas?",
  "O que devo fazer antes da minha consulta?",
];

const EXAMPLES_DE: string[] = [
  "Ich habe Brustschmerzen",
  "Ich habe Kopfschmerzen",
  "Ich habe Bauchschmerzen",
  "Ich habe Rückenschmerzen",
  "Ich habe Atemnot",
  "Ich habe Halsschmerzen",
  "Ich habe anhaltenden Husten",
  "Mir ist übel",
  "Ich habe Durchfall",
  "Ich musste mehrmals erbrechen",
  "Ich habe einen Hautausschlag",
  "Ich habe Ohrenschmerzen",
  "Meine Augen sind gerötet",
  "Meine Beine sind geschwollen",
  "Ich habe Schmerzen beim Wasserlassen",
  "Ich habe Sodbrennen",
  "Mir ist schwindlig",
  "Ich fühle mich sehr müde",
  "Ich habe Schlafprobleme",
  "Ich habe Angstsymptome",
  "Ich fühle mich depressiv",
  "Ich hatte eine Panikattacke",
  "Ich habe Zahnschmerzen",
  "Mein Knie tut weh",
  "Meine Schulter tut weh",
  "Ich habe mir den Knöchel verstaucht",
  "Ich habe mich in den Finger geschnitten",
  "Ich habe mir die Hand verbrannt",
  "Mein Blutdruck ist hoch",
  "Mein Blutzucker ist hoch",
  "Meine Temperatur ist 39 °C",
  "Mein Kind hat Fieber",
  "Mein Baby hat Fieber",
  "Mein Kind hustet",
  "Mein Kind hat Durchfall",
  "Darf ich Ibuprofen einnehmen?",
  "Darf ich Paracetamol einnehmen?",
  "Darf ich diese Medikamente kombinieren?",
  "Welche Nebenwirkungen hat dieses Medikament?",
  "Ich habe eine Dosis vergessen",
  "Hilf mir, meinen Blutbefund zu verstehen",
  "Hilf mir, meine Urinuntersuchung zu verstehen",
  "Hilf mir, mich auf den Arztbesuch vorzubereiten",
  "Erstelle Fragen für meinen Arzt",
  "Ich brauche eine Zusammenfassung für den Arzt",
  "Auf welche Symptome soll ich achten?",
  "Wann sollte ich dringend zum Arzt?",
  "Finde Hilfe in der Nähe",
  "Wie kann ich meine Symptome verfolgen?",
  "Was soll ich vor meinem Termin tun?",
];

const EXAMPLES_AR: string[] = [
  "أعاني من ألم في الصدر",
  "أعاني من صداع",
  "أعاني من ألم في المعدة",
  "أعاني من ألم في الظهر",
  "أعاني من ضيق في التنفس",
  "أعاني من التهاب الحلق",
  "أعاني من سعال مستمر",
  "أشعر بالغثيان",
  "أعاني من إسهال",
  "أعاني من قيء متكرر",
  "لدي طفح جلدي",
  "أعاني من ألم في الأذن",
  "عيناي محمرتان",
  "ساقاي منتفختان",
  "أشعر بألم عند التبول",
  "أعاني من حرقة في المعدة",
  "أشعر بالدوار",
  "أشعر بتعب شديد",
  "لدي مشاكل في النوم",
  "لدي أعراض القلق",
  "أشعر بالاكتئاب",
  "أصبت بنوبة هلع",
  "أعاني من ألم في الأسنان",
  "أعاني من ألم في الركبة",
  "أعاني من ألم في الكتف",
  "التويت كاحلي",
  "جرحت أصبعي",
  "أصبت بحروق في يدي",
  "ضغط دمي مرتفع",
  "نسبة السكر لدي مرتفعة",
  "درجة حرارتي 39 درجة مئوية",
  "طفلي مصاب بالحمى",
  "رضيعي مصاب بالحمى",
  "طفلي يعاني من السعال",
  "طفلي مصاب بالإسهال",
  "هل يمكنني تناول الإيبوبروفين؟",
  "هل يمكنني تناول الباراسيتامول؟",
  "هل يمكنني الجمع بين هذه الأدوية؟",
  "ما هي الآثار الجانبية لهذا الدواء؟",
  "نسيت جرعة من الدواء",
  "ساعدني في فهم تحليل الدم",
  "ساعدني في فهم تحليل البول",
  "ساعدني في الاستعداد لزيارة الطبيب",
  "اقترح أسئلة لأطرحها على طبيبي",
  "أحتاج إلى ملخص طبي",
  "ما الأعراض التي يجب أن أراقبها؟",
  "متى يجب أن أطلب رعاية عاجلة؟",
  "ابحث عن رعاية صحية قريبة",
  "كيف يمكنني تتبع أعراضي؟",
  "ماذا أفعل قبل موعدي الطبي؟",
];

const EXAMPLES_HI: string[] = [
  "मुझे सीने में दर्द है",
  "मुझे सिरदर्द है",
  "मुझे पेट में दर्द है",
  "मेरी पीठ में दर्द है",
  "मुझे सांस लेने में तकलीफ़ है",
  "मेरे गले में खराश है",
  "मुझे लगातार खांसी है",
  "मुझे मिचली आ रही है",
  "मुझे दस्त हो रहे हैं",
  "मुझे बार-बार उल्टी हो रही है",
  "मेरी त्वचा पर चकत्ते हैं",
  "मेरे कान में दर्द है",
  "मेरी आँखें लाल हैं",
  "मेरे पैरों में सूजन है",
  "पेशाब करते समय दर्द होता है",
  "मुझे एसिडिटी है",
  "मुझे चक्कर आ रहे हैं",
  "मुझे बहुत थकान महसूस हो रही है",
  "मुझे नींद नहीं आ रही",
  "मुझे चिंता के लक्षण हैं",
  "मैं उदास महसूस कर रहा हूँ",
  "मुझे पैनिक अटैक हुआ है",
  "मेरे दांत में दर्द है",
  "मेरे घुटने में दर्द है",
  "मेरे कंधे में दर्द है",
  "मेरी टखना मुड़ गयी है",
  "मेरी उंगली कट गई है",
  "मेरा हाथ जल गया है",
  "मेरा रक्तचाप अधिक है",
  "मेरा रक्त शर्करा अधिक है",
  "मेरा तापमान 39°C है",
  "मेरे बच्चे को बुखार है",
  "मेरे शिशु को बुखार है",
  "मेरे बच्चे को खांसी है",
  "मेरे बच्चे को दस्त हैं",
  "क्या मैं इबुप्रोफेन ले सकता हूँ?",
  "क्या मैं पैरासिटामोल ले सकता हूँ?",
  "क्या मैं ये दवाएँ एक साथ ले सकता हूँ?",
  "इस दवा के दुष्प्रभाव क्या हैं?",
  "मैं दवा की एक खुराक भूल गया",
  "मेरे रक्त परीक्षण को समझने में मदद करें",
  "मेरे मूत्र परीक्षण को समझने में मदद करें",
  "डॉक्टर की मुलाक़ात की तैयारी में मदद करें",
  "मेरे डॉक्टर के लिए प्रश्न तैयार करें",
  "मुझे डॉक्टर के लिए सारांश चाहिए",
  "मुझे किन लक्षणों पर ध्यान देना चाहिए?",
  "मुझे आपातकालीन देखभाल कब लेनी चाहिए?",
  "पास की देखभाल खोजें",
  "मैं अपने लक्षणों को कैसे ट्रैक कर सकता हूँ?",
  "अपनी मुलाक़ात से पहले मुझे क्या करना चाहिए?",
];

const EXAMPLES_ZH: string[] = [
  "我胸痛",
  "我头痛",
  "我胃痛",
  "我背痛",
  "我呼吸困难",
  "我喉咙痛",
  "我持续咳嗽",
  "我恶心",
  "我腹泻",
  "我一直在呕吐",
  "我皮肤上有皮疹",
  "我耳朵痛",
  "我眼睛发红",
  "我腿肿了",
  "我排尿时疼痛",
  "我有烧心感",
  "我头晕",
  "我感觉非常疲惫",
  "我难以入睡",
  "我有焦虑症状",
  "我感到抑郁",
  "我有过惊恐发作",
  "我牙痛",
  "我膝盖痛",
  "我肩膀痛",
  "我扭伤了脚踝",
  "我割伤了手指",
  "我手被烫伤了",
  "我的血压高",
  "我的血糖高",
  "我的体温是39°C",
  "我的孩子发烧了",
  "我的婴儿发烧了",
  "我的孩子咳嗽",
  "我的孩子腹泻",
  "我可以吃布洛芬吗？",
  "我可以吃对乙酰氨基酚吗？",
  "我可以一起服用这些药物吗？",
  "这种药有什么副作用？",
  "我漏服了一剂药",
  "帮我看懂血液检查",
  "帮我看懂尿液检查",
  "帮我为就诊做准备",
  "为我的医生准备问题",
  "我需要一份就诊摘要",
  "我应该注意哪些症状？",
  "什么时候需要紧急就医？",
  "查找附近的医疗服务",
  "我如何跟踪自己的症状？",
  "就诊前我该做什么？",
];

const EXAMPLES_JA: string[] = [
  "胸が痛みます",
  "頭痛があります",
  "腹痛があります",
  "背中が痛みます",
  "息切れがします",
  "喉が痛いです",
  "咳が止まりません",
  "吐き気があります",
  "下痢をしています",
  "嘔吐が続いています",
  "発疹が出ています",
  "耳が痛いです",
  "目が赤いです",
  "脚がむくんでいます",
  "排尿時に痛みがあります",
  "胸やけがします",
  "めまいがします",
  "とても疲れています",
  "眠れません",
  "不安の症状があります",
  "気分が落ち込んでいます",
  "パニック発作を起こしました",
  "歯が痛みます",
  "膝が痛みます",
  "肩が痛みます",
  "足首をひねりました",
  "指を切りました",
  "手をやけどしました",
  "血圧が高いです",
  "血糖値が高いです",
  "体温が39℃あります",
  "子どもが熱を出しています",
  "赤ちゃんが熱を出しています",
  "子どもが咳をしています",
  "子どもが下痢をしています",
  "イブプロフェンを飲んでもいいですか？",
  "アセトアミノフェンを飲んでもいいですか？",
  "これらの薬を一緒に飲んでも大丈夫ですか？",
  "この薬の副作用は何ですか？",
  "薬を一回飲み忘れました",
  "血液検査の結果を見てください",
  "尿検査の結果を見てください",
  "受診の準備を手伝ってください",
  "医師への質問を作成してください",
  "受診用のサマリーが欲しいです",
  "どんな症状に注意すべきですか？",
  "いつ救急を受診すべきですか？",
  "近くの医療機関を探す",
  "症状をどうやって記録すればいいですか？",
  "受診前に何をすればいいですか？",
];

const EXAMPLES_RU: string[] = [
  "У меня боль в груди",
  "У меня болит голова",
  "У меня болит живот",
  "У меня болит спина",
  "У меня одышка",
  "У меня болит горло",
  "У меня постоянный кашель",
  "Меня тошнит",
  "У меня диарея",
  "У меня была рвота",
  "У меня сыпь на коже",
  "У меня болит ухо",
  "У меня покраснели глаза",
  "У меня отекли ноги",
  "Мне больно мочиться",
  "У меня изжога",
  "У меня кружится голова",
  "Я чувствую сильную усталость",
  "Мне трудно засыпать",
  "У меня симптомы тревожности",
  "Я чувствую депрессию",
  "У меня была паническая атака",
  "У меня болит зуб",
  "У меня болит колено",
  "У меня болит плечо",
  "Я подвернул лодыжку",
  "Я порезал палец",
  "Я обжёг руку",
  "У меня высокое давление",
  "У меня высокий сахар в крови",
  "Моя температура 39 °C",
  "У моего ребёнка температура",
  "У моего малыша температура",
  "У моего ребёнка кашель",
  "У моего ребёнка диарея",
  "Можно мне принимать ибупрофен?",
  "Можно мне принимать парацетамол?",
  "Можно ли совмещать эти лекарства?",
  "Какие побочные эффекты у этого лекарства?",
  "Я пропустил приём лекарства",
  "Помоги разобраться с анализом крови",
  "Помоги разобраться с анализом мочи",
  "Помоги подготовиться к приёму у врача",
  "Составь вопросы для врача",
  "Мне нужно резюме для врача",
  "За какими симптомами мне следить?",
  "Когда обращаться за срочной помощью?",
  "Найди медицинскую помощь рядом",
  "Как мне отслеживать симптомы?",
  "Что сделать перед визитом к врачу?",
];

const EXAMPLES_NL: string[] = [
  "Ik heb pijn op de borst",
  "Ik heb hoofdpijn",
  "Ik heb buikpijn",
  "Ik heb rugpijn",
  "Ik ben kortademig",
  "Ik heb keelpijn",
  "Ik heb aanhoudende hoest",
  "Ik ben misselijk",
  "Ik heb diarree",
  "Ik moet vaak overgeven",
  "Ik heb huiduitslag",
  "Ik heb oorpijn",
  "Mijn ogen zijn rood",
  "Mijn benen zijn gezwollen",
  "Ik heb pijn bij het plassen",
  "Ik heb maagzuur",
  "Ik ben duizelig",
  "Ik voel me erg moe",
  "Ik kan niet slapen",
  "Ik heb angstklachten",
  "Ik voel me somber",
  "Ik had een paniekaanval",
  "Ik heb kiespijn",
  "Mijn knie doet pijn",
  "Mijn schouder doet pijn",
  "Ik heb mijn enkel verzwikt",
  "Ik heb in mijn vinger gesneden",
  "Ik heb mijn hand verbrand",
  "Mijn bloeddruk is hoog",
  "Mijn bloedsuiker is hoog",
  "Mijn temperatuur is 39 °C",
  "Mijn kind heeft koorts",
  "Mijn baby heeft koorts",
  "Mijn kind hoest",
  "Mijn kind heeft diarree",
  "Mag ik ibuprofen nemen?",
  "Mag ik paracetamol nemen?",
  "Mag ik deze medicijnen combineren?",
  "Wat zijn de bijwerkingen van dit medicijn?",
  "Ik ben een dosis vergeten",
  "Help me mijn bloedonderzoek te begrijpen",
  "Help me mijn urineonderzoek te begrijpen",
  "Help me me voor te bereiden op een doktersbezoek",
  "Bedenk vragen voor mijn arts",
  "Ik heb een samenvatting voor de arts nodig",
  "Op welke symptomen moet ik letten?",
  "Wanneer moet ik dringend hulp zoeken?",
  "Vind zorg in de buurt",
  "Hoe kan ik mijn symptomen bijhouden?",
  "Wat moet ik vóór mijn afspraak doen?",
];

const EXAMPLES_PL: string[] = [
  "Mam ból w klatce piersiowej",
  "Boli mnie głowa",
  "Boli mnie brzuch",
  "Boli mnie plecy",
  "Mam duszności",
  "Boli mnie gardło",
  "Mam uporczywy kaszel",
  "Mam mdłości",
  "Mam biegunkę",
  "Wymiotuję od pewnego czasu",
  "Mam wysypkę na skórze",
  "Boli mnie ucho",
  "Mam zaczerwienione oczy",
  "Mam opuchnięte nogi",
  "Boli mnie podczas oddawania moczu",
  "Mam zgagę",
  "Kręci mi się w głowie",
  "Czuję się bardzo zmęczony",
  "Mam problemy ze snem",
  "Mam objawy lękowe",
  "Czuję się przygnębiony",
  "Miałem atak paniki",
  "Boli mnie ząb",
  "Boli mnie kolano",
  "Boli mnie ramię",
  "Skręciłem kostkę",
  "Skaleczyłem palec",
  "Oparzyłem dłoń",
  "Mam wysokie ciśnienie",
  "Mam wysoki poziom cukru",
  "Moja temperatura to 39 °C",
  "Moje dziecko ma gorączkę",
  "Moje niemowlę ma gorączkę",
  "Moje dziecko kaszle",
  "Moje dziecko ma biegunkę",
  "Czy mogę wziąć ibuprofen?",
  "Czy mogę wziąć paracetamol?",
  "Czy mogę łączyć te leki?",
  "Jakie są skutki uboczne tego leku?",
  "Zapomniałem o dawce leku",
  "Pomóż mi zrozumieć wyniki badania krwi",
  "Pomóż mi zrozumieć badanie moczu",
  "Pomóż mi przygotować się do wizyty u lekarza",
  "Przygotuj pytania do lekarza",
  "Potrzebuję podsumowania dla lekarza",
  "Na jakie objawy mam zwrócić uwagę?",
  "Kiedy powinienem szukać pilnej pomocy?",
  "Znajdź pomoc w pobliżu",
  "Jak mogę monitorować objawy?",
  "Co zrobić przed wizytą u lekarza?",
];

const EXAMPLES_TR: string[] = [
  "Göğsümde ağrı var",
  "Başım ağrıyor",
  "Karnım ağrıyor",
  "Sırtım ağrıyor",
  "Nefes almakta zorlanıyorum",
  "Boğazım ağrıyor",
  "Sürekli öksürüyorum",
  "Midem bulanıyor",
  "İshalim var",
  "Sürekli kusuyorum",
  "Cildimde döküntü var",
  "Kulağım ağrıyor",
  "Gözlerim kızardı",
  "Bacaklarım şişti",
  "İdrar yaparken ağrı var",
  "Mide yanması var",
  "Başım dönüyor",
  "Çok yorgun hissediyorum",
  "Uyumakta zorlanıyorum",
  "Anksiyete belirtilerim var",
  "Kendimi depresif hissediyorum",
  "Panik atak geçirdim",
  "Dişim ağrıyor",
  "Dizim ağrıyor",
  "Omzum ağrıyor",
  "Ayak bileğimi burktum",
  "Parmağımı kestim",
  "Elimi yaktım",
  "Tansiyonum yüksek",
  "Kan şekerim yüksek",
  "Ateşim 39 °C",
  "Çocuğumun ateşi var",
  "Bebeğimin ateşi var",
  "Çocuğum öksürüyor",
  "Çocuğum ishal",
  "İbuprofen alabilir miyim?",
  "Parasetamol alabilir miyim?",
  "Bu ilaçları birlikte alabilir miyim?",
  "Bu ilacın yan etkileri nelerdir?",
  "Bir ilaç dozunu kaçırdım",
  "Kan tahlilimi anlamama yardım et",
  "İdrar tahlilimi anlamama yardım et",
  "Doktor randevusuna hazırlanmama yardım et",
  "Doktorum için sorular hazırla",
  "Doktor için bir özet istiyorum",
  "Hangi belirtilere dikkat etmeliyim?",
  "Ne zaman acil yardım aramalıyım?",
  "Yakındaki sağlık hizmetlerini bul",
  "Belirtilerimi nasıl takip edebilirim?",
  "Randevumdan önce ne yapmalıyım?",
];

const BANK: Partial<Record<SupportedLanguage, string[]>> = {
  en: EXAMPLES_EN,
  es: EXAMPLES_ES,
  fr: EXAMPLES_FR,
  it: EXAMPLES_IT,
  pt: EXAMPLES_PT,
  de: EXAMPLES_DE,
  ar: EXAMPLES_AR,
  hi: EXAMPLES_HI,
  zh: EXAMPLES_ZH,
  ja: EXAMPLES_JA,
  ru: EXAMPLES_RU,
  nl: EXAMPLES_NL,
  pl: EXAMPLES_PL,
  tr: EXAMPLES_TR,
};

/** Return the localized example-question bank for the given language,
 *  falling back to English for languages without a curated list. */
export function getExampleQuestions(language: SupportedLanguage): string[] {
  return BANK[language] ?? EXAMPLES_EN;
}

/** Pick `count` distinct items at random from the array. Pure: no
 *  reliance on global state, safe to call in render. */
export function pickRandom<T>(items: readonly T[], count: number): T[] {
  if (items.length <= count) return [...items];
  // Partial Fisher-Yates — only need the first `count` slots.
  const arr = [...items];
  for (let i = 0; i < count; i++) {
    const j = i + Math.floor(Math.random() * (arr.length - i));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, count);
}
